site_name: MetaboLights Guides
site_url: https://www.ebi.ac.uk/metabolights
theme:
  name: material
  logo: assets/metabolights.png
  favicon: assets/favicon.ico
  features:
  - content.code.annotate
  - content.code.copy
  # - content.code.select
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  # - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - navigation.sections
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  - toc.integrate
extra:
  social:
  - icon: fontawesome/brands/x-twitter
    link: https://x.com/MetaboLights
  - icon: fontawesome/brands/bluesky
    link: https://bsky.app/profile/metabolights.bsky.social
nav:
  - MetaboLights Home: https://www.ebi.ac.uk/metabolights
  - General:
    - Checklist And General:
      - MetaboLights Account: MetaboLights_account.md
      - Home: index.md
  - Submission Guide:
    - Submission overview: Study_description.md
  - MetabolomicsHub: MetabolomicsHub.md
  - Study Sections:
    - Samples: Sample.md
    - Assays: Assay.md
    - Protocols: Protocol.md
    - Metabolites: MAF.md
    - Files:
      - Files Overview: Files.md
      - Upload using Globus: Globus.md
  - Example Studies: Examples.md
  - Troubleshooting: FAQs.md
  - MetaboLights Search: Metabolights_search.md
# - Video Tutorial: Video.md
plugins:
- mkdocs-video
- search
markdown_extensions:
- def_list
- pymdownx.tasklist:
    custom_checkbox: true
# Python Markdown
- abbr:
- attr_list:
- footnotes:
- md_in_html:
- tables:
- admonition:
- toc:
    permalink: true
  # Python Markdown Extensions

- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    use_pygments: true
    linenums: false
    linenums_style: pymdownx-inline
- pymdownx.inlinehilite:
- pymdownx.snippets:
    base_path: [ "docs" ]
    check_paths: true
- pymdownx.superfences:
- pymdownx.betterem:
- pymdownx.caret:
- pymdownx.inlinehilite:
- pymdownx.keys:
- pymdownx.mark:
- pymdownx.tilde:

    # pymdownx blocks
- pymdownx.blocks.admonition:
    types:
    - note
    - attention
    - caution
    - danger
    - error
    - tip
    - hint
    - warning
    - question
    - success
    # Custom types
    - info
    - check
    - example
    - quote
- pymdownx.blocks.details:
- pymdownx.blocks.tab:
    alternate_style: True
